export const MythicGMEmulatorData = {
    eventFocusTable: [
        { range: [1, 7], description: "Remote event" },
        { range: [8, 28], description: "NPC action" },
        { range: [29, 35], description: "Introduce a new NPC" },
        { range: [36, 45], description: "Move toward a thread" },
        { range: [46, 52], description: "Move away from a thread" },
        { range: [53, 61], description: "Close a thread" },
        { range: [62, 65], description: "PC negative" },
        { range: [66, 72], description: "PC positive" },
        { range: [73, 80], description: "Ambiguous event" },
        { range: [81, 88], description: "NPC negative" },
        { range: [89, 96], description: "NPC positive" },
        { range: [97, 100], description: "Ask the GM emulator" },
    ],
    eventMeaningTable: {
        actions: [
            "Attainment",
            "Release",
            "Expose",
            "Oppress",
            "Starting",
            "Befriend",
            "Haggle",
            "Inspect",
            "Excitement",
            "Activity",
            "Neglect",
            "Fight",
            "Recruit",
            "Judge",
            "Imprison",
            "Ambush",
            "Assist",
            "Desert",
            "Release",
            "Spy",
            "Care",
            "Dominate",
            "Celebrate",
            "Attach",
            "Triumph",
            "Procrastinate",
            "Develop",
            "Carry",
            "Violate",
            "Praise",
            "Travel",
            "Open",
            "Negligence",
            "Passion",
            "Work hard",
            "Oppose",
            "Separate",
            "Block",
            "Carelessness",
            "Control",
            "Malice",
            "Take",
            "Harm",
            "Ruin",
            "Attract",
            "Communicate",
            "Break",
            "Debase",
            "Extravagance",
            "Failure",
            "Persecute",
            "Heal",
            "Overindulge",
            "Trick",
            "Pursue",
            "Increase",
            "Delay",
            "Adjourn",
            "Arrive",
            "Decrease",
            "Stop",
            "Adversity",
            "Propose",
            "Abandon",
            "Lie",
            "Kill",
            "Divide",
            "Gratify",
            "Return",
            "Disrupt",
            "Refuse",
            "Vengeance",
            "Proceedings",
            "Dispute",
            "Punish",
            "Inquire",
            "Imitate",
            "Usurp",
            "Mistrust",
            "Guide",
            "Antagonize",
            "Struggle",
            "Create",
            "Deceive",
            "Transform",
            "Move",
            "Inform",
            "Betray",
            "Cruelty",
            "Overthrow",
            "Waste",
            "Bestow",
            "Agree",
            "Intolerance",
            "Truce",
            "Postpone",
            "Abuse",
            "Trust",
            "Oppress",
            "Change",
            "Conquer",
            "Forgive",
            "Discover",
            "Defend",
            "Initiate",
            "Cherish",
            "Negotiate",
            "Examine",
            "Enthusiasm",
            "Engagement",
            "Overlook",
            "Resist",
            "Enlist",
            "Evaluate",
            "Confine",
            "Surprise",
            "Support",
            "Abandon",
            "Liberate",
            "Investigate",
            "Comfort",
            "Subdue",
            "Rejoice",
            "Connect",
            "Prevail",
            "Hesitate",
            "Evolve",
            "Transport",
            "Disregard",
            "Compliment",
            "Explore",
            "Unlock",
            "Ignorance",
            "Devotion",
            "Persevere",
            "Confront",
            "Differentiate",
            "Obstruct",
            "Recklessness",
            "Command",
            "Hostility",
            "Acquire",
            "Damage",
            "Demolish",
            "Entice",
            "Interact",
            "Shatter",
            "Degrade",
            "Lavishness",
            "Setback",
            "Harass",
            "Restore",
            "Indulge",
            "Deceive",
            "Chase",
            "Expand",
            "Postpone",
            "Suspend",
            "Reach",
            "Diminish",
            "Halt",
            "Hardship",
            "Suggest",
            "Forsake",
            "Fabricate",
            "Annihilate",
            "Separate",
            "Indulge",
            "Repay",
            "Interrupt",
            "Decline",
            "Retribution",
            "Litigation",
            "Controversy",
            "Discipline",
            "Investigate",
            "Replicate",
            "Usurp",
            "Doubt",
            "Direct",
            "Provoke",
            "Endure",
            "Generate",
            "Delude",
            "Metamorphose",
            "Progress",
            "Enlighten",
            "Deceive",
            "Severity",
            "Subvert",
            "Squander",
            "Grant",
            "Concur",
            "Bigotry",
            "Ceasefire",
            "Defer",
            "Mistreat",
            "Confidence",
            "Subjugate",
            "Alter"
,        ],
        subjects: [
            "Goals",
            "Messages",
            "Dreams",
            "Energy",
            "Environment",
            "Balance",
            "Competition",
            "Outside",
            "Tension",
            "Advice",
            "A plot",
            "Prison",
            "Death",
            "Victory",
            "Disruption",
            "Dispute",
            "Power",
            "Riches",
            "A burden",
            "Inside",
            "Friendship",
            "Illness",
            "Intrigues",
            "Reality",
            "The physical",
            "Food",
            "Fears",
            "Status quo",
            "Technology",
            "Hope",
            "Allies",
            "A project",
            "Attention",
            "Ambush",
            "Enemies",
            "Pleasures",
            "Success",
            "Rumor",
            "Magic",
            "Illusions",
            "Evil",
            "Good",
            "Emotions",
            "Opposition",
            "War",
            "Pain",
            "Possessions",
            "Benefits",
            "Plans",
            "Failure",
            "Wounds",
            "Portals",
            "Travel",
            "Extravagance",
            "Danger",
            "Jealousy",
            "Dispute",
            "A representative",
            "Adversities",
            "Weapons",
            "Animals",
            "Home",
            "Opulence",
            "Weather",
            "Lies",
            "Peace",
            "Expectations",
            "Investment",
            "Liberty",
            "The innocent",
            "Legal matters",
            "Suffering",
            "Military",
            "Love",
            "Bureaucracy",
            "Wishes",
            "The mundane",
            "The spiritual",
            "The intellectual",
            "New ideas",
            "Joy",
            "News",
            "Business",
            "Tactics",
            "A path",
            "Exterior factors",
            "Misfortune",
            "Stalemate",
            "Randomness",
            "Trials",
            "Masses",
            "Vehicle",
            "Art",
            "Elements",
            "Nature",
            "The public",
            "Leadership",
            "Fame",
            "Anger",
            "Information",
            "Motivation",
            "Communication",
            "Imagination",
            "Passion",
            "Conservation",
            "Harmony",
            "Rivalry",
            "Exploration",
            "Stress",
            "Guidance",
            "Strategy",
            "Captivity",
            "Rebirth",
            "Conquest",
            "Chaos",
            "Conflict",
            "Influence",
            "Wealth",
            "Responsibility",
            "Introspection",
            "Companionship",
            "Disease",
            "Mystery",
            "Perception",
            "Materialism",
            "Nourishment",
            "Anxiety",
            "Innovation",
            "Science",
            "Optimism",
            "Partners",
            "Initiative",
            "Focus",
            "Deception",
            "Adversaries",
            "Indulgence",
            "Achievement",
            "Gossip",
            "Enchantment",
            "Delusions",
            "Malevolence",
            "Benevolence",
            "Sentiments",
            "Resistance",
            "Battle",
            "Suffering",
            "Assets",
            "Rewards",
            "Intentions",
            "Loss",
            "Injuries",
            "Gateways",
            "Journey",
            "Luxury",
            "Peril",
            "Envy",
            "Argument",
            "Spokesperson",
            "Challenges",
            "Arsenal",
            "Creatures",
            "Sanctuary",
            "Splendor",
            "Climate",
            "Deceit",
            "Tranquility",
            "Anticipation",
            "Venture",
            "Freedom",
            "Purity",
            "Justice",
            "Torment",
            "Strategy",
            "Affection",
            "Red tape",
            "Desires",
            "Ordinary",
            "Divinity",
            "Intellect",
            "Innovation",
            "Contentment",
            "Announcement",
            "Commerce",
            "Maneuvers",
            "Direction",
            "External forces",
            "Calamity",
            "Standstill",
            "Uncertainty",
            "Tests",
            "Crowds",
            "Transport",
            "Expression",
            "Fundamentals",
            "Wildlife",
            "Society",
            "Authority",
            "Renown",
            "Resentment",
            "Knowledge"
        ],
    },

    eventMeaningTableElements: {
        locations: [
            "Abandoned ",
            "Active ",
            "Artistic ",
            "Atmosphere ",
            "Beautiful ",
            "Bleak ",
            "Bright ",
            "Business ",
            "Calm ",
            "Charming ",
            "Clean ",
            "Cluttered ",
            "Cold ",
            "Colorful ",
            "Colorless ",
            "Confusing ",
            "Cramped ",
            "Creepy ",
            "Crude ",
            "Cute ",
            "Damaged ",
            "Dangerous ",
            "Dark ",
            "Delightful ",
            "Dirty ",
            "Domestic ",
            "Empty ",
            "Enclosed ",
            "Enormous ",
            "Entrance ",
            "Exclusive ",
            "Exposed ",
            "Extravagant ",
            "Familiar ",
            "Fancy ",
            "Festive ",
            "Foreboding ",
            "Fortunate ",
            "Fragrant ",
            "Frantic ",
            "Frightening ",
            "Full ",
            "Harmful ",
            "Helpful ",
            "Horrible ",
            "Important ",
            "Impressive ",
            "Inactive ",
            "Intense ",
            "Intriguing ",
            "Lively ",
            "Lonely ",
            "Long ",
            "Loud ",
            "Meaningful ",
            "Messy ",
            "Mobile ",
            "Modern ",
            "Mundane ",
            "Mysterious ",
            "Natural ",
            "New ",
            "Occupied ",
            "Odd ",
            "Official ",
            "Old ",
            "Open ",
            "Peaceful ",
            "Personal ",
            "Plain ",
            "Portal ",
            "Protected ",
            "Protection ",
            "Purposeful ",
            "Quiet ",
            "Reassuring ",
            "Remote ",
            "Resourceful ",
            "Ruined ",
            "Rustic ",
            "Safe ",
            "Services ",
            "Simple ",
            "Small ",
            "Spacious ",
            "Storage ",
            "Strange ",
            "Stylish ",
            "Suspicious ",
            "Tall ",
            "Threatening ",
            "Tranquil ",
            "Unexpected ",
            "Unpleasant ",
            "Unusual ",
            "Useful ",
            "Warm ",
            "Warning ",
            "Watery ",
            "Welcoming"
        ],
        characters: [
            "Accompanied",
            "Active",
            "Aggressive",
            "Ambush",
            "Animal",
            "Anxious",
            "Armed",
            "Beautiful",
            "Bold",
            "Busy",
            "Calm",
            "Careless",
            "Casual",
            "Cautious",
            "Classy",
            "Colorful",
            "Combative",
            "Crazy",
            "Creepy",
            "Curious",
            "Dangerous",
            "Deceitful",
            "Defeated",
            "Defiant",
            "Delightful",
            "Emotional",
            "Energetic",
            "Equipped",
            "Excited",
            "Expected",
            "Familiar",
            "Fast",
            "Feeble",
            "Feminine",
            "Ferocious",
            "Foe",
            "Foolish",
            "Fortunate",
            "Fragrant",
            "Frantic",
            "Friend",
            "Frightened",
            "Frightening",
            "Generous",
            "Glad",
            "Happy",
            "Harmful",
            "Helpful",
            "Helpless",
            "Hurt",
            "Important",
            "Inactive",
            "Influential",
            "Innocent",
            "Intense",
            "Knowledgeable",
            "Large",
            "Lonely",
            "Loud",
            "Loyal",
            "Masculine",
            "Mighty",
            "Miserable",
            "Multiple",
            "Mundane",
            "Mysterious",
            "Natural",
            "Odd",
            "Official",
            "Old",
            "Passive",
            "Peaceful",
            "Playful",
            "Powerful",
            "Professional",
            "Protected",
            "Protecting",
            "Questioning",
            "Quiet",
            "Reassuring",
            "Resourceful",
            "Seeking",
            "Skilled",
            "Slow",
            "Small",
            "Stealthy",
            "Strange",
            "Strong",
            "Tall",
            "Thieving",
            "Threatening",
            "Triumphant",
            "Unexpected",
            "Unnatural",
            "Unusual",
            "Violent",
            "Vocal",
            "Weak",
            "Wild",
            "Young"
        ],
        objects: [
            "Active",
            "Artistic",
            "Average",
            "Beautiful",
            "Bizarre",
            "Bright",
            "Clothing",
            "Clue",
            "Cold",
            "Colorful",
            "Communication",
            "Complicated",
            "Confusing",
            "Consumable",
            "Container",
            "Creepy",
            "Crude",
            "Cute",
            "Damaged",
            "Dangerous",
            "Deactivated",
            "Deliberate",
            "Delightful",
            "Desired",
            "Domestic",
            "Empty",
            "Energy",
            "Enormous",
            "Equipment",
            "Expected",
            "Expended",
            "Extravagant",
            "Faded",
            "Familiar",
            "Fancy",
            "Flora",
            "Fortunate",
            "Fragile",
            "Fragrant",
            "Frightening",
            "Garbage",
            "Guidance",
            "Hard",
            "Harmful",
            "Healing",
            "Heavy",
            "Helpful",
            "Horrible",
            "Important",
            "Inactive",
            "Information",
            "Intriguing",
            "Large",
            "Lethal",
            "Light",
            "Liquid",
            "Loud",
            "Majestic",
            "Meaningful",
            "Mechanical",
            "Modern",
            "Moving",
            "Multiple",
            "Mundane",
            "Mysterious",
            "Natural",
            "New",
            "Odd",
            "Official",
            "Old",
            "Ornamental",
            "Ornate",
            "Personal",
            "Powerful",
            "Prized",
            "Protection",
            "Rare",
            "Ready",
            "Reassuring",
            "Resource",
            "Ruined",
            "Small",
            "Soft",
            "Solitary",
            "Stolen",
            "Strange",
            "Stylish",
            "Threatening",
            "Tool",
            "Travel",
            "Unexpected",
            "Unpleasant",
            "Unusual",
            "Useful",
            "Useless",
            "Valuable",
            "Warm",
            "Weapon",
            "Wet",
            "Worn"
        ],
    },

    oracleProbabilityTable: [
        { probability: "A Sure Thing", odds: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] },
        { probability: "A Near Sure Thing", odds: [1, 1, 1, 1, 1, 1, 1, 1, 1, 2] },
        { probability: "Very Likely", odds: [1, 1, 1, 1, 1, 1, 1, 1, 2, 2] },
        { probability: "Likely", odds: [1, 1, 1, 1, 1, 1, 1, 2, 2, 3] },
        { probability: "Somewhat Likely", odds: [1, 1, 1, 1, 1, 1, 2, 2, 3, 4] },
        { probability: "50/50", odds: [1, 1, 1, 1, 1, 2, 2, 3, 4, 5] },
        { probability: "Somewhat Unlikely", odds: [1, 1, 1, 1, 2, 2, 3, 4, 5, 6] },
        { probability: "Unlikely", odds: [1, 1, 1, 2, 2, 3, 4, 5, 6, 7] },
        { probability: "Very Unlikely", odds: [1, 1, 2, 2, 3, 4, 5, 6, 7, 8] },
        { probability: "A Near Impossible", odds: [1, 2, 2, 3, 4, 5, 6, 7, 8, 9] },
        { probability: "Impossible", odds: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      ],
}