export const nameData = {
    British: {
        AngloSaxon: {
            male: {
                prefixes: ['Ac-', 'Aelf-', 'Aenes-', 'Aethel-', 'Aew-', 'Ard-', 'Arm-', 'Baerh-', 'Barda-', 'Bay-', 'Beald-', 'Bel-', 'Beo-', 'Beorht-', 'Beorn-', 'Beran-', 'Bitan-', 'Blac-', 'Blaec-', 'Blaed-', 'Bland-', 'Bote-', 'Bregu-', 'Brun-', 'Burg-', 'Cadda-', 'Caed-', 'Cen-', 'Ceol-', 'Cuic-', 'Cuth-', 'Cyne-', 'Daeg-', 'Daegel-', 'Daegga-', 'Deal-', 'Deor-', 'Dern-', 'Dude-', 'Dun-', 'Ead-', 'Eald-', 'Ealh-', 'Ean-', 'Ear-', 'Ecg-', 'Eofor-', 'Frea-', 'Frith-', 'Gar-', 'Geat-', 'Gisel-', 'Glaed-', 'God-', 'Gold-', 'Graeg-', 'Grim-', 'Guth-', 'Halig-', 'Hard-', 'Hari-', 'Heah-', 'Heana-', 'Heard-', 'Heathu-', 'Helm-', 'Heort-', 'Here-', 'Herle-', 'Hlot-', 'Hoga-', 'Holen-', 'Hrof-', 'Hroth-', 'Hun-', 'Hwit-', 'In-', 'Isen-', 'Kettil-', 'Lang-', 'Leod-', 'Leof-', 'Mael-', 'Maer-', 'Maht-', 'Mund-', 'North-', 'Noth-', 'Oe-', 'Ondes-', 'Ord-', 'Orme-', 'Os-', 'Rand-', 'Raegen-', 'Read-', 'Ric-', 'Rim-', 'Ruh-', 'Run-', 'Sa-', 'Sae-', 'Scroc-', 'Secg-', 'Sel-', 'Sig-', 'Sige-', 'Snel-', 'Stan-', 'Strang-', 'Sunu-', 'Swet-', 'Swith-', 'Theod-', 'Thur-', 'Tila-', 'Tort-', 'Treuwe-', 'Trum-', 'Wacer-', 'Waer-', 'Wald-', 'Walt-', 'Weald-', 'Weard-', 'Wict-', 'Wig-', 'Wil-', 'Wine-', 'Wulf-', 'Wusc-'],
                suffixes: ['-eldra', '-aesc', '-arm', '-beald', '-beorht', '-beorn', '-bert', '-bote', '-brand', '-cromb', '-cyne', '-deal', '-deor', '-dreda', '-ecg', '-eofer', '-frea', '-frith', '-fugol', '-gar', '-gard', '-geat', '-gild', '-glaed', '-god', '-gold', '-grim', '-gyr', '-haele', '-hard', '-heah', '-heard', '-helm', '-here', '-hun', '-in', '-kettil', '-lac', '-leod', '-leof', '-mael', '-maer', '-maht', '-mann', '-mon', '-mund', '-noth', '-nyd', '-raed', '-rand', '-ric', '-rim', '-run', '-sele', '-sig', '-sige', '-snel', '-son', '-stan', '-sterre', '-strang', '-sunu', '-swith', '-thorne', '-uald', '-wacer', '-waer', '-wald', '-walh', '-walt', '-weald', '-weard', '-weorth', '-wict', '-wig', '-wil', '-wine', '-wini', '-wise', '-wold', '-wulf', '-wyn'],
            },
            female: {
                prefixes: ['Ac-', 'Aelf-', 'Aenes-', 'Aethel-', 'Aew-', 'Ard-', 'Arm-', 'Baerh-', 'Barda-', 'Bay-', 'Beald-', 'Bel-', 'Beo-', 'Beorht-', 'Beorn-', 'Beran-', 'Bitan-', 'Blac-', 'Blaec-', 'Blaed-', 'Bland-', 'Bote-', 'Bregu-', 'Brun-', 'Burg-', 'Cadda-', 'Caed-', 'Cen-', 'Ceol-', 'Cuic-', 'Cuth-', 'Cwen-', 'Cyne-', 'Daeg-', 'Daegel-', 'Daegga-', 'Deal-', 'Deor-', 'Dern-', 'Dude-', 'Dun-', 'Ead-', 'Eald-', 'Ealh-', 'Ean-', 'Ear-', 'Ecg-', 'Eofor-', 'Frea-', 'Frith-', 'Gar-', 'Geat-', 'Gisel-', 'Glaed-', 'God-', 'Gold-', 'Graeg-', 'Grim-', 'Gunn-', 'Guth-', 'Halig-', 'Hard-', 'Hari-', 'Heah-', 'Heana-', 'Heard-', 'Heathu-', 'Helm-', 'Heort-', 'Here-', 'Herle-', 'Hild-', 'Hlot-', 'Hoga-', 'Holen-', 'Hrof-', 'Hroth-', 'Hun-', 'Hwit-', 'In-', 'Isen-', 'Kettil-', 'Lang-', 'Leod-', 'Leof-', 'Mael-', 'Maer-', 'Maht-', 'Mild-', 'Mund-', 'North-', 'Noth-', 'Oc-', 'Ondes-', 'Ord-', 'Orme-', 'Os-', 'Raegen-', 'Rand-', 'Read-', 'Ric-', 'Rim-', 'Ruh-', 'Run-', 'Sa-', 'Sae-', 'Secg-', 'Sele-', 'Sig-', 'Sige-', 'Snel-', 'Stan-', 'Strang-', 'Sunu-', 'Swet-', 'Swith-', 'Theod-', 'Thur-', 'Tila-', 'Tort-', 'Treuwe-', 'Trum-', 'Tun-', 'Wacer-', 'Waer-', 'Wald-', 'Walt-', 'Weald-', 'Weard-', 'Wict-', 'Wig-', 'Wil-', 'Wine-', 'Wulf-', 'Wusc-'],
                suffixes: ['-aeldra', '-aesc', '-arm', '-beald', '-beorht', '-beorn', '-bert', '-bote', '-brand', '-burg', '-cromb', '-cyne', '-deal', '-deor', '-dreda', '-ecg', '-eofer', '-flaed', '-frea', '-frith', '-fugol', '-gar', '-geat', '-gifu', '-gild', '-glaed', '-god', '-gold', '-grim', '-gyr', '-gyth', '-haele', '-hard', '-heah', '-heard', '-helm', '-here', '-hild', '-hun', '-in', '-kettil', '-lac', '-leod', '-leofu', '-ma', '-mael', '-maer', '-maht', '-mon', '-noth', '-nyd', '-or', '-raed', '-rand', '-ric', '-rim', '-run', '-sele', '-sig', '-sige', '-snel', '-son', '-stan', '-sterre', '-strang', '-sunu', '-swith', '-thorne', '-thryth', '-uald', '-wacer', '-wald', '-walh', '-waru', '-walt', '-weald', '-weard', '-weorth', '-wict', '-wig', '-wil', '-wini', '-wise', '-wold', '-wulf', '-wyn', '-wythe'],
            },
        },
        Cornish: {
            male: {
                prefixes: ['Alan-', 'Alun-', 'Arthur-', 'Arthyen-', 'Austell-', 'Benesek-', 'Blyth-', 'Branek-', 'Branwalather-', 'Brengy-', 'Breoc-', 'Bryok-', 'Budic-', 'Buthek-', 'Cadan-', 'Cador-', 'Cadreth-', 'Caradoc-', 'Carasek-', 'Carrow-', 'Caswyn-', 'Cleder-', 'Clemow-', 'Clesek-', 'Colan-', 'Colyn-', 'Corentyn-', 'Cornelly-', 'Costentyn-', 'Costetyn-', 'Crantok-', 'Credan-', 'Daveth-', 'Davy-', 'Denzel-', 'Digory-', 'Docco-', 'Doniert-', 'Donyerth-', 'Durngarth-', 'Elid-', 'Enoder-', 'Ervan-', 'Feoc-', 'Gawen-', 'Gerens-', 'Gerent-', 'Germoc-', 'Germoe-', 'Glewas-', 'Goran-', 'Gorlas-', 'Goron-', 'Gorthelyk-', 'Gourgy-', 'Gwinear-', 'Gwynek-', 'Herygh-', 'Hicca-', 'Howel-', 'Hydroc-', 'Iahan-', 'Ives-', 'Jacca-', 'Jago-', 'Jamma-', 'Jory-', 'Jowan-', 'Kaveran-', 'Kenal-', 'Kenan-', 'Kenver-', 'Kenwyn-', 'Keresyk-', 'Kevern-', 'Kitto-', 'Ludwan-', 'Maban-', 'Madern-', 'Malgen-', 'Manuel-', 'Margh-', 'Marrek-', 'Massen-', 'Mawgan-', 'Maylwen-', 'Mellyan-', 'Melor-', 'Melyn-', 'Meriasek-', 'Merryn-', 'Milyan-', 'Myghal-', 'Nadelek-', 'Nechtan-', 'Nerth-', 'Neythen-', 'Nicca-', 'Padern-', 'Pasco-', 'Pawly-', 'Peder-', 'Pencast-', 'Peran-', 'Perran-', 'Petroc-', 'Petrok-', 'Piran-', 'Rewan-', 'Ruan-', 'Rumon-', 'Ryel-', 'Samson-', 'Seleven-', 'Selyf-', 'Sennen-', 'Silyen-', 'Sithny-', 'Sythyn-', 'Talan-', 'Talek-', 'Tomas-', 'Trevedic-', 'Tristan-', 'Trystan-', 'Udy-', 'Uther-', 'Uthno-', 'Vark-', 'Vyvyan-', 'Welet-', 'Wella-', 'Weryn-', 'Wethinoc-', 'Withell-', 'Worrec-', 'Yestin-', 'Ythel-'],
                suffixes: ['Andrewartha-', 'Angrave-', 'Annear-', 'Anning-', 'Bain-', 'Baragwanath-', 'Beckerleg-', 'Bedell-', 'Bennetto-', 'Bennetts-', 'Berriman-', 'Berryman-', 'Bescoby-', 'Bice-', 'Biddick-', 'Binney-', 'Blamey-', 'Boase-', 'Boden-', 'Bolitho-', 'Bonython-', 'Borlase-', 'Bosanko-', 'Bosanquet-', 'Bray-', 'Briddon-', 'Bryant-', 'Carbines-', 'Cardell-', 'Care-', 'Carlyon-', 'Carnell-', 'Carveth-', 'Causley-', 'Chegwidden-', 'Chenhalls-', 'Chenoweth-', 'Clemow-', 'Clemson-', 'Climo-', 'Clymo-', 'Coad-', 'Cocking-', 'Colenso-', 'Colley-', 'Congdon-', 'Corin-', 'Couch-', 'Cowling-', 'Craddick-', 'Crago-', 'Craze-', 'Crowle-', 'Cundy-', 'Curnow-', 'Daniel-', 'Deveril-', 'Dobell-', 'Dowling-', 'Eade-', 'Edwards-', 'Ellis-', 'Endean-', 'Eva-', 'Faull-', 'Frayne-', 'Freeman-', 'Freethy-', 'Galtey-', 'Geach-', 'Geake-', 'Godden-', 'Gole-', 'Goss-', 'Gribbin-', 'Gynn-', 'Hain-', 'Haines-', 'Hambly-', 'Hannaford-', 'Hannah-', 'Harris-', 'Hayne-', 'Hendra-', 'Hobby-', 'Hocking-', 'Hodge-', 'Hollow-', 'Hosking-', 'Hoskins-', 'Inch-', 'Isbell-', 'Ivey-', 'James-', 'Jasper-', 'Jelbart-', 'Jennings-', 'Jewell-', 'Johns-', 'Joliffe-', 'Jolly-', 'Keast-', 'Keen-', 'Keigwin-', 'Kempthorne-', 'Kersey-', 'Kestle-', 'Kinver-', 'Kittow-', 'Lander-', 'Landreth-', 'Lanyon-', 'Lawry-', 'Lean-', 'Leggo-', 'Liddicoat-', 'Lowry-', 'Maddaford-', 'Maddern-', 'Magor-', 'Martin-', 'Mayne-', 'Menadue-', 'Mitchell-', 'Moon-', 'Morcom-', 'Murrish-', 'Nancarrow-', 'Nankervis-', 'Nankivel-', 'Newth-', 'Nicholls-', 'Ninnis-', 'Noall-', 'Noon-', 'Oates-', 'Odgers-', 'Old-', 'Olver-', 'Opie-', 'Otes-', 'Palk-', 'Pascoe-', 'Pawley-', 'Paynter-', 'Pearce-', 'Pellew-', 'Penberthy-', 'Pender-', 'Pengelly-', 'Penhaligon-', 'Penhallow-', 'Penn-', 'Penrose-', 'Pentreath-', 'Penwarden-', 'Perkin-', 'Perrin-', 'Peters-', 'Pethick-', 'Phillips-', 'Poldark-', 'Polmear-', 'Praed-', 'Prowse-', 'Quick-', 'Quintrell-', 'Raddall-', 'Restorick-'],
            },
            female: {
                prefixes: ['Ailla-', 'Angelet-', 'Arranz-', 'Athwenna-', 'Banallan-', 'Barenwyn-', 'Berlewen-', 'Bersaba-', 'Beryan-', 'Blejan-', 'Bryluen-', 'Burien-', 'Caja-', 'Carenza-', 'Ceinwen-', 'Chesten-', 'Columba-', 'Conwenna-', 'Cordelia-', 'Crewenna-', 'Cryda-', 'Delen-', 'Demelza-', 'Derowen-', 'Derwa-', 'Dywana-', 'Ebrel-', 'Elestren-', 'Elowen-', 'Endelienta-', 'Endelyon-', 'Eseld-', 'Eselt-', 'Esyld-', 'Eva-', 'Ewa-', 'Ewe-', 'Glanna-', 'Gweniver-', 'Gwennol-', 'Hedra-', 'Jenifer-', 'Jenifry-', 'Jenna-', 'Jowanet-', 'Kayna-', 'Kelynen-', 'Kensa-', 'Kerensa-', 'Kerenza-', 'Keresyk-', 'Kerra-', 'Kew-', 'Ladoca-', 'Loveday-', 'Lowenek-', 'Lowenna-', 'Mabyn-', 'Manacca-', 'Mariot-', 'Marya-', 'Melior-', 'Meliora-', 'Mellear-', 'Melloney-', 'Mellyn-', 'Melwyn-', 'Melyar-', 'Melyonen-', 'Melyor-', 'Meraud-', 'Merouda-', 'Metheven-', 'Morenwyn-', 'Morgelyn-', 'Morveren-', 'Morvoren-', 'Morwen-', 'Morwenna-', 'Morwennol-', 'Morwetha-', 'Neraud-', 'Nessa-', 'Newlyn-', 'Newlyna-', 'Nonna-', 'Rosen-', 'Rozen-', 'Rozenwyn-', 'Senara-', 'Sevi-', 'Sowena-', 'Steren-', 'Talwyn-', 'Tamara-', 'Tamsyn-', 'Tecca-', 'Tegen-', 'Tregereth-', 'Tressa-', 'Trevenna-', 'Tryfena-', 'Vorva-', 'Weneppa-', 'Wenn-', 'Wenna-', 'Wylmet-', 'Ygerna-', 'Zethar-'],
                suffixes: ['Andrewartha-', 'Angrave-', 'Annear-', 'Anning-', 'Bain-', 'Baragwanath-', 'Beckerleg-', 'Bedell-', 'Bennetto-', 'Bennetts-', 'Berriman-', 'Berryman-', 'Bescoby-', 'Bice-', 'Biddick-', 'Binney-', 'Blamey-', 'Boase-', 'Boden-', 'Bolitho-', 'Bonython-', 'Borlase-', 'Bosanko-', 'Bosanquet-', 'Bray-', 'Briddon-', 'Bryant-', 'Carbines-', 'Cardell-', 'Care-', 'Carlyon-', 'Carnell-', 'Carveth-', 'Causley-', 'Chegwidden-', 'Chenhalls-', 'Chenoweth-', 'Clemow-', 'Clemson-', 'Climo-', 'Clymo-', 'Coad-', 'Cocking-', 'Colenso-', 'Colley-', 'Congdon-', 'Corin-', 'Couch-', 'Cowling-', 'Craddick-', 'Crago-', 'Craze-', 'Crowle-', 'Cundy-', 'Curnow-', 'Daniel-', 'Deveril-', 'Dobell-', 'Dowling-', 'Eade-', 'Edwards-', 'Ellis-', 'Endean-', 'Eva-', 'Faull-', 'Frayne-', 'Freeman-', 'Freethy-', 'Galtey-', 'Geach-', 'Geake-', 'Godden-', 'Gole-', 'Goss-', 'Gribbin-', 'Gynn-', 'Hain-', 'Haines-', 'Hambly-', 'Hannaford-', 'Hannah-', 'Harris-', 'Hayne-', 'Hendra-', 'Hobby-', 'Hocking-', 'Hodge-', 'Hollow-', 'Hosking-', 'Hoskins-', 'Inch-', 'Isbell-', 'Ivey-', 'James-', 'Jasper-', 'Jelbart-', 'Jennings-', 'Jewell-', 'Johns-', 'Joliffe-', 'Jolly-', 'Keast-', 'Keen-', 'Keigwin-', 'Kempthorne-', 'Kersey-', 'Kestle-', 'Kinver-', 'Kittow-', 'Lander-', 'Landreth-', 'Lanyon-', 'Lawry-', 'Lean-', 'Leggo-', 'Liddicoat-', 'Lowry-', 'Maddaford-', 'Maddern-', 'Magor-', 'Martin-', 'Mayne-', 'Menadue-', 'Mitchell-', 'Moon-', 'Morcom-', 'Murrish-', 'Nancarrow-', 'Nankervis-', 'Nankivel-', 'Newth-', 'Nicholls-', 'Ninnis-', 'Noall-', 'Noon-', 'Oates-', 'Odgers-', 'Old-', 'Olver-', 'Opie-', 'Otes-', 'Palk-', 'Pascoe-', 'Pawley-', 'Paynter-', 'Pearce-', 'Pellew-', 'Penberthy-', 'Pender-', 'Pengelly-', 'Penhaligon-', 'Penhallow-', 'Penn-', 'Penrose-', 'Pentreath-', 'Penwarden-', 'Perkin-', 'Perrin-', 'Peters-', 'Pethick-', 'Phillips-', 'Poldark-', 'Polmear-', 'Praed-', 'Prowse-', 'Quick-', 'Quintrell-', 'Raddall-', 'Restorick-'],
            },
        },
    }
}