const npcModifierTable = [
        { value: 1, modifier: "superfluous" },
        { value: 2, modifier: "addicted" },
        { value: 3, modifier: "conformist" },
        { value: 4, modifier: "nefarious" },
        { value: 5, modifier: "sensible" },
        { value: 6, modifier: "untrained" },
        { value: 7, modifier: "romantic" },
        { value: 8, modifier: "unreasonable" },
        { value: 9, modifier: "skilled" },
        { value: 10, modifier: "neglectful" },
        { value: 11, modifier: "lively" },
        { value: 12, modifier: "forthright" },
        { value: 13, modifier: "idealistic" },
        { value: 14, modifier: "unsupportive" },
        { value: 15, modifier: "rational" },
        { value: 16, modifier: "coarse" },
        { value: 17, modifier: "foolish" },
        { value: 18, modifier: "cunning" },
        { value: 19, modifier: "delightful" },
        { value: 20, modifier: "miserly" },
        { value: 21, modifier: "inept" },
        { value: 22, modifier: "banal" },
        { value: 23, modifier: "logical" },
        { value: 24, modifier: "subtle" },
        { value: 25, modifier: "reputable" },
        { value: 26, modifier: "wicked" },
        { value: 27, modifier: "lazy" },
        { value: 28, modifier: "pessimistic" },
        { value: 29, modifier: "solemn" },
        { value: 30, modifier: "habitual" },
        { value: 31, modifier: "meek" },
        { value: 32, modifier: "helpful" },
        { value: 33, modifier: "unconcerned" },
        { value: 34, modifier: "generous" },
        { value: 35, modifier: "docile" },
        { value: 36, modifier: "cheery" },
        { value: 37, modifier: "pragmatic" },
        { value: 38, modifier: "serene" },
        { value: 39, modifier: "thoughtful" },
        { value: 40, modifier: "hopeless" },
        { value: 41, modifier: "pleasant" },
        { value: 42, modifier: "insensitive" },
        { value: 43, modifier: "titled" },
        { value: 44, modifier: "inexperienced" },
        { value: 45, modifier: "prying" },
        { value: 46, modifier: "oblivious" },
        { value: 47, modifier: "refined" },
        { value: 48, modifier: "indispensable" },
        { value: 49, modifier: "scholarly" },
        { value: 50, modifier: "conservative" },
        { value: 51, modifier: "uncouth" },
        { value: 52, modifier: "willful" },
        { value: 53, modifier: "indifferent" },
        { value: 54, modifier: "fickle" },
        { value: 55, modifier: "elderly" },
        { value: 56, modifier: "sinful" },
        { value: 57, modifier: "naive" },
        { value: 58, modifier: "privileged" },
        { value: 59, modifier: "glum" },
        { value: 60, modifier: "likable" },
        { value: 61, modifier: "lethargic" },
        { value: 62, modifier: "defiant" },
        { value: 63, modifier: "obnoxious" },
        { value: 64, modifier: "insightful" },
        { value: 65, modifier: "tactless" },
        { value: 66, modifier: "fanatic" },
        { value: 67, modifier: "plebeian" },
        { value: 68, modifier: "childish" },
        { value: 69, modifier: "pious" },
        { value: 70, modifier: "uneducated" },
        { value: 71, modifier: "inconsiderate" },
        { value: 72, modifier: "cultured" },
        { value: 73, modifier: "revolting" },
        { value: 74, modifier: "curious" },
        { value: 75, modifier: "touchy" },
        { value: 76, modifier: "needy" },
        { value: 77, modifier: "dignified" },
        { value: 78, modifier: "pushy" },
        { value: 79, modifier: "kind" },
        { value: 80, modifier: "corrupt" },
        { value: 81, modifier: "jovial" },
        { value: 82, modifier: "shrewd" },
        { value: 83, modifier: "liberal" },
        { value: 84, modifier: "compliant" },
        { value: 85, modifier: "destitute" },
        { value: 86, modifier: "conniving" },
        { value: 87, modifier: "careful" },
        { value: 88, modifier: "alluring" },
        { value: 89, modifier: "defective" },
        { value: 90, modifier: "optimistic" },
        { value: 91, modifier: "affluent" },
        { value: 92, modifier: "despondent" },
        { value: 93, modifier: "mindless" },
        { value: 94, modifier: "passionate" },
        { value: 95, modifier: "devoted" },
        { value: 96, modifier: "established" },
        { value: 97, modifier: "unseemly" },
        { value: 98, modifier: "dependable" },
        { value: 99, modifier: "righteous" },
        { value: 100, modifier: "confident" }
    ]
    
const npcNounTable = [
        { value: 1, noun: "gypsy" },
        { value: 2, noun: "witch" },
        { value: 3, noun: "merchant" },
        { value: 4, noun: "expert" },
        { value: 5, noun: "commoner" },
        { value: 6, noun: "judge" },
        { value: 7, noun: "ranger" },
        { value: 8, noun: "occultist" },
        { value: 9, noun: "reverend" },
        { value: 10, noun: "thug" },
        { value: 11, noun: "drifter" },
        { value: 12, noun: "journeyman" },
        { value: 13, noun: "statesman" },
        { value: 14, noun: "astrologer" },
        { value: 15, noun: "duelist" },
        { value: 16, noun: "jack-of-all-trades" },
        { value: 17, noun: "aristocrat" },
        { value: 18, noun: "preacher" },
        { value: 19, noun: "artisan" },
        { value: 20, noun: "rogue" },
        { value: 21, noun: "missionary" },
        { value: 22, noun: "outcast" },
        { value: 23, noun: "mercenary" },
        { value: 24, noun: "caretaker" },
        { value: 25, noun: "hermit" },
        { value: 26, noun: "orator" },
        { value: 27, noun: "chieftain" },
        { value: 28, noun: "pioneer" },
        { value: 29, noun: "burglar" },
        { value: 30, noun: "vicar" },
        { value: 31, noun: "officer" },
        { value: 32, noun: "explorer" },
        { value: 33, noun: "warden" },
        { value: 34, noun: "outlaw" },
        { value: 35, noun: "adept" },
        { value: 36, noun: "bum" },
        { value: 37, noun: "sorcerer" },
        { value: 38, noun: "laborer" },
        { value: 39, noun: "master" },
        { value: 40, noun: "ascendant" },
        { value: 41, noun: "villager" },
        { value: 42, noun: "magus" },
        { value: 43, noun: "conscript" },
        { value: 44, noun: "worker" },
        { value: 45, noun: "actor" },
        { value: 46, noun: "herald" },
        { value: 47, noun: "highwayman" },
        { value: 48, noun: "fortune-hunter" },
        { value: 49, noun: "governor" },
        { value: 50, noun: "scrapper" },
        { value: 51, noun: "monk" },
        { value: 52, noun: "homemaker" },
        { value: 53, noun: "recluse" },
        { value: 54, noun: "steward" },
        { value: 55, noun: "polymath" },
        { value: 56, noun: "magician" },
        { value: 57, noun: "traveler" },
        { value: 58, noun: "vagrant" },
        { value: 59, noun: "apprentice" },
        { value: 60, noun: "politician" },
        { value: 61, noun: "mediator" },
        { value: 62, noun: "crook" },
        { value: 63, noun: "civilian" },
        { value: 64, noun: "activist" },
        { value: 65, noun: "hero" },
        { value: 66, noun: "champion" },
        { value: 67, noun: "cleric" },
        { value: 68, noun: "slave" },
        { value: 69, noun: "gunman" },
        { value: 70, noun: "clairvoyant" },
        { value: 71, noun: "patriarch" },
        { value: 72, noun: "shopkeeper" },
        { value: 73, noun: "crone" },
        { value: 74, noun: "adventurer" },
        { value: 75, noun: "soldier" },
        { value: 76, noun: "entertainer" },
        { value: 77, noun: "craftsman" },
        { value: 78, noun: "scientist" },
        { value: 79, noun: "ascetic" },
        { value: 80, noun: "superior" },
        { value: 81, noun: "performer" },
        { value: 82, noun: "magister" },
        { value: 83, noun: "serf" },
        { value: 84, noun: "brute" },
        { value: 85, noun: "inquisitor" },
        { value: 86, noun: "lord" },
        { value: 87, noun: "villain" },
        { value: 88, noun: "professor" },
        { value: 89, noun: "servant" },
        { value: 90, noun: "charmer" },
        { value: 91, noun: "globetrotter" },
        { value: 92, noun: "sniper" },
        { value: 93, noun: "courtier" },
        { value: 94, noun: "priest" },
        { value: 95, noun: "tradesman" },
        { value: 96, noun: "hitman" },
        { value: 97, noun: "wizard" },
        { value: 98, noun: "beggar" },
        { value: 99, noun: "tradesman" },
        { value: 100, noun: "warrior" }
    ]

    const npcPowerLevelTable = [
        {
          rLevel: "Order",
          ranges: [
            { range: [1, 2], description: "Much Weaker" },
            { range: [3, 10], description: "Slightly Weaker" },
            { range: [11, 90], description: "Comparable" },
            { range: [91, 98], description: "Slightly Stronger" },
            { range: [99, 100], description: "Much Stronger" },
          ],
        },
        {
            rLevel: "Calm",
            ranges: [
              { range: [1, 4], description: "Much Weaker" },
              { range: [5, 15], description: "Slightly Weaker" },
              { range: [16, 86], description: "Comparable" },
              { range: [86, 96], description: "Slightly Stronger" },
              { range: [97, 100], description: "Much Stronger" },
            ],
          },
          {
            rLevel: "Standard",
            ranges: [
              { range: [1, 5], description: "Much Weaker" },
              { range: [6, 20], description: "Slightly Weaker" },
              { range: [21, 80], description: "Comparable" },
              { range: [81, 95], description: "Slightly Stronger" },
              { range: [96, 100], description: "Much Stronger" },
            ],
          },
          {
            rLevel: "Disarray",
            ranges: [
              { range: [1, 8], description: "Much Weaker" },
              { range: [9,25], description: "Slightly Weaker" },
              { range: [26, 75], description: "Comparable" },
              { range: [76, 92], description: "Slightly Stronger" },
              { range: [93, 100], description: "Much Stronger" },
            ],
          },
          {
            rLevel: "Chaos",
            ranges: [
              { range: [1, 12], description: "Much Weaker" },
              { range: [13, 30], description: "Slightly Weaker" },
              { range: [31, 70], description: "Comparable" },
              { range: [71, 88], description: "Slightly Stronger" },
              { range: [89, 100], description: "Much Stronger" },
            ],
          },
      ];
    
      const npcMotivationVerbTable = [
        { value: 1, verb: "Advise" },
        { value: 2, verb: "Obtain" },
        { value: 3, verb: "Attempt" },
        { value: 4, verb: "Spoil" },
        { value: 5, verb: "Oppress" },
        { value: 6, verb: "Interact" },
        { value: 7, verb: "Create" },
        { value: 8, verb: "Abduct" },
        { value: 9, verb: "Promote" },
        { value: 10, verb: "Conceive" },
        { value: 11, verb: "Blight" },
        { value: 12, verb: "Progress" },
        { value: 13, verb: "Distress" },
        { value: 14, verb: "Possess" },
        { value: 15, verb: "Record" },
        { value: 16, verb: "Embrace" },
        { value: 17, verb: "Contact" },
        { value: 18, verb: "Pursue" },
        { value: 19, verb: "Associate" },
        { value: 20, verb: "Prepare" },
        { value: 21, verb: "Shepherd" },
        { value: 22, verb: "Abuse" },
        { value: 23, verb: "Indulge" },
        { value: 24, verb: "Chronicle" },
        { value: 25, verb: "Fulfill" },
        { value: 26, verb: "Drive" },
        { value: 27, verb: "Review" },
        { value: 28, verb: "Aid" },
        { value: 29, verb: "Follow" },
        { value: 30, verb: "Advance" },
        { value: 31, verb: "Guard" },
        { value: 32, verb: "Conquer" },
        { value: 33, verb: "Hinder" },
        { value: 34, verb: "Plunder" },
        { value: 35, verb: "Construct" },
        { value: 36, verb: "Encourage" },
        { value: 37, verb: "Agonize" },
        { value: 38, verb: "Comprehend" },
        { value: 39, verb: "Administer" },
        { value: 40, verb: "Relate" },
        { value: 41, verb: "Take" },
        { value: 42, verb: "Discover" },
        { value: 43, verb: "Deter" },
        { value: 44, verb: "Acquire" },
        { value: 45, verb: "Damage" },
        { value: 46, verb: "Publicize" },
        { value: 47, verb: "Burden" },
        { value: 48, verb: "Advocate" },
        { value: 49, verb: "Implement" },
        { value: 50, verb: "Understand" },
        { value: 51, verb: "Collaborate" },
        { value: 52, verb: "Strive" },
        { value: 53, verb: "Complete" },
        { value: 54, verb: "Compel" },
        { value: 55, verb: "Join" },
        { value: 56, verb: "Assist" },
        { value: 57, verb: "Defile" },
        { value: 58, verb: "Produce" },
        { value: 59, verb: "Institute" },
        { value: 60, verb: "Account" },
        { value: 61, verb: "Work" },
        { value: 62, verb: "Accompany" },
        { value: 63, verb: "Offend" },
        { value: 64, verb: "Guide" },
        { value: 65, verb: "Learn" },
        { value: 66, verb: "Persecute" },
        { value: 67, verb: "Communicate" },
        { value: 68, verb: "Process" },
        { value: 69, verb: "Report" },
        { value: 70, verb: "Develop" },
        { value: 71, verb: "Steal" },
        { value: 72, verb: "Suggest" },
        { value: 73, verb: "Weaken" },
        { value: 74, verb: "Achieve" },
        { value: 75, verb: "Secure" },
        { value: 76, verb: "Inform" },
        { value: 77, verb: "Patronize" },
        { value: 78, verb: "Depress" },
        { value: 79, verb: "Determine" },
        { value: 80, verb: "Seek" },
        { value: 81, verb: "Manage" },
        { value: 82, verb: "Suppress" },
        { value: 83, verb: "Proclaim" },
        { value: 84, verb: "Operate" },
        { value: 85, verb: "Access" },
        { value: 86, verb: "Refine" },
        { value: 87, verb: "Compose" },
        { value: 88, verb: "Undermine" },
        { value: 89, verb: "Explain" },
        { value: 90, verb: "Discourage" },
        { value: 91, verb: "Attend" },
        { value: 92, verb: "Detect" },
        { value: 93, verb: "Execute" },
        { value: 94, verb: "Maintain" },
        { value: 95, verb: "Realize" },
        { value: 96, verb: "Convey" },
        { value: 97, verb: "Rob" },
        { value: 98, verb: "Establish" },
        { value: 99, verb: "Attempt" },
        { value: 100, verb: "Spoil" },
      ];
      const npcMotivationNounTable = [
        { value: 1, noun: "Wealth" },
        { value: 2, noun: "Hardship" },
        { value: 3, noun: "Affluence" },
        { value: 4, noun: "Resources" },
        { value: 5, noun: "Prosperity" },
        { value: 6, noun: "Poverty" },
        { value: 7, noun: "Opulence" },
        { value: 8, noun: "Deprivation" },
        { value: 9, noun: "Success" },
        { value: 10, noun: "Distress" },
        { value: 11, noun: "Contraband" },
        { value: 12, noun: "Music" },
        { value: 13, noun: "Literature" },
        { value: 14, noun: "Technology" },
        { value: 15, noun: "Alcohol" },
        { value: 16, noun: "Medicines" },
        { value: 17, noun: "Beauty" },
        { value: 18, noun: "Strength" },
        { value: 19, noun: "Intelligence" },
        { value: 20, noun: "Force" },
        { value: 21, noun: "The Wealthy" },
        { value: 22, noun: "The Populous" },
        { value: 23, noun: "Enemies" },
        { value: 24, noun: "The Public" },
        { value: 25, noun: "Religion" },
        { value: 26, noun: "The Poor" },
        { value: 27, noun: "Family" },
        { value: 28, noun: "The Elite" },
        { value: 29, noun: "Academia" },
        { value: 30, noun: "The Forsaken" },
        { value: 31, noun: "The Law" },
        { value: 32, noun: "The Government" },
        { value: 33, noun: "The Oppressed" },
        { value: 34, noun: "Friends" },
        { value: 35, noun: "Criminals" },
        { value: 36, noun: "Allies" },
        { value: 37, noun: "Secret Societies" },
        { value: 38, noun: "The World" },
        { value: 39, noun: "Military" },
        { value: 40, noun: "The Church" },
        { value: 41, noun: "Dreams" },
        { value: 42, noun: "Discretion" },
        { value: 43, noun: "Love" },
        { value: 44, noun: "Freedom" },
        { value: 45, noun: "Pain" },
        { value: 46, noun: "Faith" },
        { value: 47, noun: "Slavery" },
        { value: 48, noun: "Enlightenment" },
        { value: 49, noun: "Racism" },
        { value: 50, noun: "Sensuality" },
        { value: 51, noun: "Dissonance" },
        { value: 52, noun: "Peace" },
        { value: 53, noun: "Discrimination" },
        { value: 54, noun: "Disbelief" },
        { value: 55, noun: "Pleasure" },
        { value: 56, noun: "Hate" },
        { value: 57, noun: "Happiness" },
        { value: 58, noun: "Servitude" },
        { value: 59, noun: "Harmony" },
        { value: 60, noun: "Justice" },
        { value: 61, noun: "Gluttony" },
        { value: 62, noun: "Lust" },
        { value: 63, noun: "Envy" },
        { value: 64, noun: "Greed" },
        { value: 65, noun: "Laziness" },
        { value: 66, noun: "Wrath" },
        { value: 67, noun: "Pride" },
        { value: 68, noun: "Purity" },
        { value: 69, noun: "Moderation" },
        { value: 70, noun: "Vigilance" },
        { value: 71, noun: "Zeal" },
        { value: 72, noun: "Composure" },
        { value: 73, noun: "Charity" },
        { value: 74, noun: "Modesty" },
        { value: 75, noun: "Atrocities" },
        { value: 76, noun: "Cowardice" },
        { value: 77, noun: "Narcissism" },
        { value: 78, noun: "Compassion" },
        { value: 79, noun: "Valor" },
        { value: 80, noun: "Patience" },
        { value: 81, noun: "Advice" },
        { value: 82, noun: "Propaganda" },
        { value: 83, noun: "Science" },
        { value: 84, noun: "Knowledge" },
        { value: 85, noun: "Communications" },
        { value: 86, noun: "Lies" },
        { value: 87, noun: "Myths" },
        { value: 88, noun: "Riddles" },
        { value: 89, noun: "Stories" },
        { value: 90, noun: "Legends" },
        { value: 91, noun: "Industry" },
        { value: 92, noun: "New Religions" },
        { value: 93, noun: "Progress" },
        { value: 94, noun: "Animals" },
        { value: 95, noun: "Ghosts" },
        { value: 96, noun: "Magic" },
        { value: 97, noun: "Nature" },
        { value: 98, noun: "Old Religions" },
        { value: 99, noun: "Expertise" },
        { value: 100, noun: "Spirits" },
      ];      

      const npcMoodTable = [
        {
          npcRelationship: "loved",
          ranges: [
            { range: [1], description: "Withdrawn" },
            { range: [2, 6], description: "Guarded" },
            { range: [7, 16], description: "Cautious" },
            { range: [17, 31], description: "Neutral" },
            { range: [32, 70], description: "Sociable" },
            { range: [71, 85], description: "Helpful" },
            { range: [86, 100], description: "Forthcoming" }
          ]
        },
        {
          npcRelationship: "friendly",
          ranges: [
            { range: [1, 2], description: "Withdrawn" },
            { range: [3, 8], description: "Guarded" },
            { range: [9, 20], description: "Cautious" },
            { range: [21, 40], description: "Neutral" },
            { range: [41, 76], description: "Sociable" },
            { range: [77, 89], description: "Helpful" },
            { range: [90, 100], description: "Forthcoming" }
          ]
        },
        {
          npcRelationship: "peaceful",
          ranges: [
            { range: [1, 3], description: "Withdrawn" },
            { range: [4, 11], description: "Guarded" },
            { range: [12, 25], description: "Cautious" },
            { range: [26, 55], description: "Neutral" },
            { range: [56, 82], description: "Sociable" },
            { range: [83, 93], description: "Helpful" },
            { range: [94, 100], description: "Forthcoming" }
          ]
        },
        {
          npcRelationship: "neutral",
          ranges: [
            { range: [1, 5], description: "Withdrawn" },
            { range: [6, 15], description: "Guarded" },
            { range: [16, 30], description: "Cautious" },
            { range: [31, 60], description: "Neutral" },
            { range: [71, 85], description: "Sociable" },
            { range: [86, 95], description: "Helpful" },
            { range: [96, 100], description: "Forthcoming" }
          ]
        },
        {
          npcRelationship: "distrustful",
          ranges: [
            { range: [1, 7], description: "Withdrawn" },
            { range: [8, 18], description: "Guarded" },
            { range: [19, 46], description: "Cautious" },
            { range: [47, 76], description: "Neutral" },
            { range: [77, 90], description: "Sociable" },
            { range: [91, 97], description: "Helpful" },
            { range: [98, 100], description: "Forthcoming" }
          ]
        },
        {
          npcRelationship: "hostile",
          ranges: [
            { range: [1, 11], description: "Withdrawn" },
            { range: [12, 24], description: "Guarded" },
            { range: [25, 61], description: "Cautious" },
            { range: [62, 81], description: "Neutral" },
            { range: [82, 93], description: "Sociable" },
            { range: [94, 98], description: "Helpful" },
            { range: [99, 100], description: "Forthcoming" }
          ]
        },
        {
         npcRelationship: "hated",
         ranges: [
            { range: [1, 15], description: "Withdrawn" },
            { range: [16, 30], description: "Guarded" },
            { range: [31, 69], description: "Cautious" },
            { range: [70, 84], description: "Neutral" },
            { range: [85, 94], description: "Sociable" },
            { range: [95, 99], description: "Helpful" },
            { range: [100], description: "Forthcoming" }
         ]
        }
        ];      

        const npcBearingTable = {
          demeanors: [
            { range: [1, 12], demeanor: "scheming" },
            { range: [13, 24], demeanor: "insane" },
            { range: [25, 36], demeanor: "friendly" },
            { range: [37, 49], demeanor: "hostile" },
            { range: [50, 62], demeanor: "inquisitive" },
            { range: [63, 75], demeanor: "knowing" },
            { range: [76, 88], demeanor: "mysterious" },
            { range: [89, 100], demeanor: "prejudiced" },
          ],
          bearings: {
            scheming: [
              { range: [1, 10], description: "intent" },
              { range: [11, 20], description: "bargain" },
              { range: [21, 30], description: "means" },
              { range: [31, 40], description: "proposition" },
              { range: [41, 50], description: "plan" },
              { range: [51, 60], description: "compromise" },
              { range: [61, 70], description: "agenda" },
              { range: [71, 80], description: "arrangement" },
              { range: [81, 90], description: "negotiation" },
              { range: [91, 100], description: "plot" },
            ],
            insane: [
              { range: [1, 10], description: "madness" },
              { range: [11, 20], description: "fear" },
              { range: [21, 30], description: "accident" },
              { range: [31, 40], description: "chaos" },
              { range: [41, 50], description: "idiocy" },
              { range: [51, 60], description: "illusion" },
              { range: [61, 70], description: "turmoil" },
              { range: [71, 80], description: "confusion" },
              { range: [81, 90], description: "facade" },
              { range: [91, 100], description: "bewilderment" },
            ],
            friendly: [
              { range: [1, 10], description: "alliance" },
              { range: [11, 20], description: "comfort" },
              { range: [21, 30], description: "gratitude" },
              { range: [31, 40], description: "shelter" },
              { range: [41, 50], description: "happiness" },
              { range: [51, 60], description: "support" },
              { range: [61, 70], description: "promise" },
              { range: [71, 80], description: "delight" },
              { range: [81, 90], description: "aid" },
              { range: [91, 100], description: "celebration" },
            ],
            hostile: [
              { range: [1, 10], description: "death" },
              { range: [11, 20], description: "capture" },
              { range: [21, 30], description: "judgement" },
              { range: [31, 40], description: "combat" },
              { range: [41, 50], description: "surrender" },
              { range: [51, 60], description: "rage" },
              { range: [61, 70], description: "resentment" },
              { range: [71, 80], description: "submission" },
              { range: [81, 90], description: "injury" },
              { range: [91, 100], description: "destruction" },
            ],
            inquisitive: [
              { range: [1, 10], description: "questions" },
              { range: [11, 20], description: "investigation" },
              { range: [21, 30], description: "interest" },
              { range: [31, 40], description: "demand" },
              { range: [41, 50], description: "suspicion" },
              { range: [51, 60], description: "request" },
              { range: [61, 70], description: "curiosity" },
              { range: [71, 80], description: "skepticism" },
              { range: [81, 90], description: "command" },
              { range: [91, 100], description: "petition" },
            ],
            knowing: [
              { range: [1, 10], description: "report" },
              { range: [11, 20], description: "effects" },
              { range: [21, 30], description: "examination" },
              { range: [31, 40], description: "records" },
              { range: [41, 50], description: "account" },
              { range: [51, 60], description: "news" },
              { range: [61, 70], description: "history" },
              { range: [71, 80], description: "telling" },
              { range: [81, 90], description: "discourse" },
              { range: [91, 100], description: "speech" },
            ],
            mysterious: [
              { range: [1, 10], description: "rumor" },
              { range: [11, 20], description: "uncertainty" },
              { range: [21, 30], description: "secrets" },
              { range: [31, 40], description: "misdirection" },
              { range: [41, 50], description: "whispers" },
              { range: [51, 60], description: "lies" },
              { range: [61, 70], description: "shadows" },
              { range: [71, 80], description: "enigma" },
              { range: [81, 90], description: "obscurity" },
              { range: [91, 100], description: "conundrum" },
            ],
            prejudiced: [
              { range: [1, 10], description: "reputation" },
              { range: [11, 20], description: "doubt" },
              { range: [21, 30], description: "bias" },
              { range: [31, 40], description: "dislike" },
              { range: [41, 50], description: "partiality" },
              { range: [51, 60], description: "belief" },
              { range: [61, 70], description: "view" },
              { range: [71, 80], description: "discrimination" },
              { range: [81, 90], description: "assessment" },
              { range: [91, 100], description: "difference" },
            ],
          },
        };

        const npcFocusTable = [  
          { range: [1, 3], description: "current scene" },
          { range: [4, 6], description: "last story" },
          { range: [7, 9], description: "equipment" },
          { range: [10, 12], description: "parents" },
          { range: [13, 15], description: "history" },
          { range: [16, 18], description: "retainers" },
          { range: [19, 21], description: "wealth" },
          { range: [22, 24], description: "relics" },
          { range: [25, 27], description: "last action" },
          { range: [28, 30], description: "skills" },
          { range: [31, 33], description: "superiors" },
          { range: [34, 36], description: "fame" },
          { range: [37, 39], description: "campaign" },
          { range: [40, 42], description: "future action" },
          { range: [43, 45], description: "friends" },
          { range: [46, 48], description: "allies" },
          { range: [49, 51], description: "last scene" },
          { range: [52, 54], description: "contacts" },
          { range: [55, 57], description: "flaws" },
          { range: [58, 60], description: "antagonist" },
          { range: [61, 63], description: "rewards" },
          { range: [64, 66], description: "experience" },
          { range: [67, 69], description: "knowledge" },
          { range: [70, 72], description: "recent scene" },
          { range: [73, 75], description: "community" },
          { range: [76, 78], description: "treasure" },
          { range: [79, 81], description: "the character" },
          { range: [82, 84], description: "current story" },
          { range: [85, 87], description: "family" },
          { range: [88, 90], description: "power" },
          { range: [91, 93], description: "weapons" },
          { range: [94, 96], description: "previous scene" },
          { range: [97, 100], description: "enemy" },
        ];

        
      export { npcModifierTable, npcNounTable, npcPowerLevelTable, npcMotivationVerbTable, npcMotivationNounTable, npcMoodTable, npcBearingTable, npcFocusTable };